id: ICCDF4A17
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:02:49+00:00'
last_modified: '2022-06-10T05:29:38.559599+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4982
  title: བྱང་ཆུབ་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AB00:
      image_group_id: I3CN4984
      title: Volume 1 of byang chub lam/
      total_pages: 183
      order: 1
      base_file: AB00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
